version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  redis:
    image: redis

  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=mnm

  influxdb:
    image: influxdb:1.2
    ports:
      - "8083:8083"
      - "8086:8086"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./compose/grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - "GF_SERVER_ROOT_URL=https://localhost:3000"
      - "GF_SECURITY_ADMIN_PASSWORD=secret"
      - "GF_INSTALL_PLUGINS=grafana-piechart-panel,vonage-status-panel,grafana-worldmap-panel"

  celeryworker: &base_app
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    volumes:
        - .:/app
    depends_on:
     - postgres
     - redis
    command: celery -A mnm.taskapp worker -l DEBUG -Q crawl,messaging,statuses,celery,default
    env_file: .env
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,0.0.0.0
      - POSTGRES_USER=mnm
      - USE_DOCKER=yes
      - INFLUXDB_URL=influxdb://root:root@influxdb:8086/test

  django:
    <<: *base_app
    command: /start-dev.sh
    ports:
      - "8000:8000"

  celerybeat:
    <<: *base_app
    command: celery -A mnm.taskapp beat -l INFO

  bot:
    <<: *base_app
    command: python manage.py start_bot
